version: "3"

services:
  mysqldb:
    image: mysql:5.7
    healthcheck:
      test: [ "CMD", "sh", "-c", "echo \> /dev/tcp/localhost/3306 && echo \'Port is open\'" ]
      timeout: 30s
      interval: 2s
      retries: 15
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 3
        window: 30s
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    #restart: always
    environment:
      - WORDPRESS_DB_HOST=mysqldb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
